Gps and imu test scripts
bbrk24/BSC_Arduino pull request #22
Opened 2024-02-07 19:42 UTC by DarthSethious1

2024-02-07 19:43 UTC, DarthSethious1 commented
I should've been uploading bit by bit, sorry it's a large PR now

2024-02-07 21:41 UTC, TheRoyalIrishman approved these changes
This looks good to me - I trust your work

2024-02-07 23:03 UTC, bbrk24 requested changes
First time reviewing a PR on mobile so I might have missed something or some comments might show up in the wrong place. Hopefully what I mean is clear enough.

2024-02-07 23:03 UTC, bbrk24 commented on CAPS_INF.CSV
I thought this file (the .CSV) wasn't supposed to be checked in?

2024-02-07 23:03 UTC, bbrk24 commented on gps.h
> +  m_phase++; \
Edit to add: I want to be clear that this is the most serious concern out of all the comments I left.

A backslash at the end of a line means to act like it's all on one line, so this (`m_phase++`) is actually part of the comment!
The way macros work in C/C++, the body of the `#define` has to be all one line. I used backslashes to make it take up multiple lines to be easier to read, but the downside is that `//`-style comments can't go in the middle of it. Either delete the comment, or change it to the `/*...*/` style.

2024-02-07 23:03 UTC, bbrk24 commented on gps.h
> +      //Serial.print("Has not started I2C comms, attempting now...");
I would either delete these entirely, or lock them behind some condition rather than commenting them out. Commenting out code is fine for local testing, but rarely belongs on master.

2024-02-07 23:03 UTC, bbrk24 commented on test_GPS.ino
> +    Serial.print("Unable to read values for some reason...");
Not gonna hold up the PR over this, but this one should probably be println

2024-02-07 23:03 UTC, bbrk24 commented on test_IMU.ino
> +/* THIS IS FOR STATIC TEST
Same as above about commented-out code

2024-02-07 23:03 UTC, bbrk24 commented on test_IMU.ino
> +    fakeCoords.timestamp.seconds += (unsigned int)1;
You don't need to cast constants. If you really want to be sure, you can put the letter U after it (i.e. `1U`) to make it an unsigned constant, but that usually isn't necessary.

2024-02-07 23:03 UTC, bbrk24 commented on test_IMU.ino
> +  fakeCoords.timestamp.milliseconds += (unsigned int)shortDelay;
`shortDelay` should probably be unsigned anyways.

2024-02-08 13:30 UTC, DarthSethious1 commented on gps.h
> +  m_phase++; \
I will start deleting all 'Serial.println' when it comes to merging with master

2024-02-08 13:38 UTC, TheRoyalIrishman commented on CAPS_INF.CSV
I thought so too - I thought I added it to the .gitignore in master

2024-02-08 14:12 UTC, DarthSethious1 commented on test_IMU.ino
> +    fakeCoords.timestamp.seconds += (unsigned int)1;
IDK how, but I didn't see this the first time. It was giving me trouble when I didn't cast it to the appropriate type. When I cast it like this it stopped giving me trouble.

2024-02-08 14:34 UTC, bbrk24 commented on test_IMU.ino
>    if (int(fakeCoords.timestamp.milliseconds) >= 1000){
I missed this the first time around, but I believe this could instead be written
```cpp
if (fakeCoords.timestamp.milliseconds >= 1000U) {
```

2024-02-08 14:40 UTC, bbrk24 approved these changes

2024-02-08 14:40 UTC, merged